name: 'Deploy to Cloudfront'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Build
      uses: | 
        npm install 
        npm run build

    - name: Push to S3
      run: | 
        pushd build
        aws s3 cp . s3://www.trype.com/ --recursive --acl public-read-write
        popd
    
    - name: Invalidate Cloudfront cache
      run: | 
        aws cloudfront   create-invalidation --distribution-id ${{CF_ROOT_DISTRIBUTION_ID}} --paths "/*"
        aws cloudfront   create-invalidation --distribution-id ${{CF_WWW_DISTRIBUTION_ID}} --paths "/*"
       
